FROM node:24-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
RUN chown node:node /usr/src/app
USER node
COPY --chown=node:node ["package.json", "package-lock.json*", "./"]
RUN npm install --silent
COPY --chown=node:node . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
